# Generated by Django 4.1.3 on 2022-12-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('reastaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reastaurant',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reastaurents_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='reastaurant',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, related_name='reastaurants_foods', to='reastaurant.food'),
        ),
        migrations.AddField(
            model_name='reastaurant',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='reastaurant_image_name', to='reastaurant.image'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_categories', to='reastaurant.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ManyToManyField(null=True, to='reastaurant.image'),
        ),
        migrations.AddField(
            model_name='food',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='reastaurant.item'),
        ),
    ]
