# Generated by Django 4.1.3 on 2022-12-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reastaurant', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='reastaurant.item'),
        ),
    ]
