# Generated by Django 4.1.3 on 2022-12-12 09:33

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('reastaurant', '0003_alter_food_image_alter_food_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('food', models.ManyToManyField(related_name='restaurants_foods', to='reastaurant.food')),
                ('image', models.ManyToManyField(related_name='restaurant_image_name', to='reastaurant.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Reastaurant',
        ),
    ]
