# Generated by Django 4.1.3 on 2022-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reastaurant', '0003_remove_item_food_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reastaurant',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, related_name='reastaurants_foods', to='reastaurant.food'),
        ),
    ]
