# Generated by Django 4.1.3 on 2022-12-14 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reastaurant', '0005_restaurant_phone_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('food', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reastaurant.food')),
                ('res', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reastaurant.restaurant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cart_food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
