# Generated by Django 4.1.3 on 2022-12-14 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reastaurant', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='res',
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reastaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_cart_food', to=settings.AUTH_USER_MODEL),
        ),
    ]
