# Generated by Django 4.1.3 on 2022-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reastaurant', '0006_alter_reastaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/img'),
        ),
    ]
