# Generated by Django 4.1.3 on 2022-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reastaurant', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
