# Generated by Django 4.1.3 on 2022-12-12 09:33

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reastaurant', '0004_restaurant_delete_reastaurant'),
        ('address', '0003_auto_20200830_1851'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
